draw_config:
  key_w: 60.0
  key_h: 50.0
  split_gap: 30.0
  append_colon_to_layer_header: true
  shrink_wide_legends: 6
  footer_text: "Osman Azo - Split keyboard with trackpad and encoder"

parse_config:
  skip_binding_parsing: false
  layer_legend_map:
    "default": "DEF"
    "raise": "⇧"
    "lower": "⇩"
  raw_binding_map:
    # Layer access - using the exact bindings from your keymap
    "&mo RAISE": {t: "⇧", h: "raise", type: "held"}
    "&mo 1": {t: "⇧", h: "raise", type: "held"}
    # Bluetooth controls
    "&bt BT_CLR": "BT CLR"
    # Common Mac shortcuts
    "&kp LG(X)": "⌘X"
    "&kp LG(C)": "⌘C"
    "&kp LG(V)": "⌘V"
    # Arrow keys with symbols
    "&kp UP": "↑"
    "&kp DOWN": "↓"
    "&kp LEFT": "←"
    "&kp RIGHT": "→"
    # Special keys
    "&kp GRAVE": "`"
    "&kp BSPC": "⌫"
    "&kp DEL": "⌦"
    "&kp TAB": "⇥"
    "&kp ENTER": "⏎"
    "&kp SPACE": "␣"
    "&kp ESC": "⎋"
    "&kp CAPS": "⇪"
    "&kp HOME": "⇤"
    "&kp END": "⇥"
