manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ahmed-m-osman1
      url-base: https://github.com/Ahmed-M-Osman1
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-driver-azoteq
      remote: ahmed-m-osman1
      # branch
      revision: fix-double-wait
  self:
    path: config
